version: '2'

services:
  web:
    container_name: nestjs_boilerplate
    build:
      context: .
      dockerfile: DockerfileLocal
    ports:
      - '3000:3000'
      - '5870:5870'
    env_file: .env
    volumes:
      - .:/src:cached
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
volumes:
  db_data:
